-- 코드를 입력하세요


SELECT I.INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS S 
INNER JOIN ICECREAM_INFO AS I
ON S.FLAVOR = I.FLAVOR
GROUP BY  I.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC;